### ISSUE TITLE
Module not found: 'rc-queue-anim' 

### ISSUE THREAD

**Issue by luajoy** [react-component/banner-anim#10]
dva项目,通过命令 npm install rc-banner-anim --save 安装之后，
在js中通过导入 rc-banner-anim 报错：
## Uncaught Error: Cannot find module "rc-queue-anim" ...
![2](https://user-images.githubusercontent.com/10186460/28806925-3e5dee3e-76a5-11e7-9acd-366c905926c9.png)

但是使用 antd-mobile 等模块却没问题，是需要配置什么东西吗？谢谢

**Comment by jljsj33** [comment]
`npm instal rc-queue-anim --save` 了吗？

**Comment by jljsj33** [comment]
照这个使用吧。。。。https://github.com/ant-motion/ant-motion-dva-cli-example

**Comment by jljsj33** [comment]
照这个使用吧。。。。https://github.com/ant-motion/ant-motion-dva-cli-example
