### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Seasons123** [react-component/banner-anim#11]
想问一下[这行的代码](https://github.com/react-component/banner-anim/blob/master/src/anim.jsx#L149)中的``${gridWidth + 1}px``是属于什么语法？（看着不是jQuery也不像EL表达式。。  :sweat_smile:   ）

**Comment by jljsj33** [comment]
es6 的 [link](http://babeljs.io/learn-es2015/#ecmascript-2015-features-template-strings)

**Comment by Seasons123** [comment]
好的，谢谢 :tada:
