### ISSUE TITLE
BannerAnim自动播放时设置dragPlay={false}导致播放时间异常

### ISSUE THREAD

**Issue by gfwu** [react-component/banner-anim#18]
<BannerAnim
	prefixCls="banner-user"
	autoPlay
	dragPlay={false}
	onChange={this.onChange}
>			
</BannerAnim>
比如：autoPlaySpeed设置5秒，第一张banner在播放3秒时切换第二张banner，第二张banner只能停留2秒

**Comment by jljsj33** [comment]
Thx, 2.0.2 fix
