### ISSUE TITLE
banner-anim crashed when using antd grid inside Element

### ISSUE THREAD

**Issue by itsmaqsoodecommdesk** [react-component/banner-anim#35]
There are two elements under BannerAnim. One used antd Grid (Row, Column) , & rc-tween-one animation inside Antd Title, another is empty. Switching element several times, the page will report an error and crash

### index.js:1375 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Element`.
    in Element (at Home.jsx:38)
    in div (created by BannerAnim)
    in BannerAnim (at Home.jsx:37)
    in div (at Home.jsx:33)
    in div (at Home.jsx:31)
    in Home (created by Context.Consumer)
    in Route (at App.js:51)
    in App (at src/index.js:20)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:19)
    in Provider (at src/index.js:18)

**Comment by jljsj33** [comment]
Need Reproduce，https://codesandbox.io/s/42vvz4j4yx

**Comment by itsmaqsoodecommdesk** [comment]
Please check it, after changing slider for random times you will the error
https://codesandbox.io/s/determined-ritchie-vk88m

**Comment by jljsj33** [comment]
fixed, but it is not recommended that you use anything other than `rc-tween-one, rc-queue-anim, rc-animate, BgElement` in `Element`.
