### ISSUE TITLE
banner项数量大于等于3, 且设置了背景, 在拖动切换的过程中, 后面的banner项背景会覆盖掉banner项

### ISSUE THREAD

**Issue by VoliBearCat** [react-component/banner-anim#58]
banner项数量大于等于3, 且设置了背景, 在拖动切换的过程中, 后面的banner项背景会覆盖掉banner项
如demo:
http://react-component.github.io/banner-anim/examples/change.html

在切换的过程中, 第一项和第三项的z-index是相同的, 所以后面的banner项的会覆盖前面.

**Comment by jljsj33** [comment]
fix in https://github.com/react-component/banner-anim/commit/be210bdd0c664f294ed102b4f7d68f3023ac5a01
