### ISSUE TITLE
当key为0的时候，BannerAnim. getRenderChildren 报错，但是react支持这种逻辑

### ISSUE THREAD

**Issue by iwege** [react-component/banner-anim#9]
报错地址为：
https://github.com/react-component/banner-anim/blob/master/src/BannerAnim.jsx#L102

常规情况下，拿到数组之后会直接
```!jsx
 var children  = data.map((val,key)=>{<element key={key} />});
```
在这种情况下直接判断`!item.key`是不正确的。

目前的workaroud是将key变为字符串。这样才正常。

**Comment by jljsj33** [comment]
```jsx
 const children = data.map((val, key) => (<element key={`${key}`} />));
```
建议不要直接 number。。。。转一下吧。。。

**Comment by jljsj33** [comment]
https://facebook.github.io/react/docs/lists-and-keys.html#extracting-components-with-keys 官方建义 key 是转成 string 类型的。。。

**Comment by iwege** [comment]
明白了，能在error里面提一句么？
